#!/bin/sh

read -r RICETHEME < "${HOME}"/.config/bspwm/.rice

# Autostart
xrandr --output Virtual-1 --mode 1920x1080 &
xsetroot _cursor_name left_ptr &
numlockx &
nitrogen --restore &

# Установить 10 рабочих столов
bspc monitor -d 1 2 3 4 5

# Window settings
bspc config border_width    1 
bspc config window_gap      12

bspc config normal_border_color     "#7DCFFF"
bpsc config active_border_color     "#000000"
bspc config focused_border_color    "#0A9CF5"


bspc config presel_feedback_color   "#a5c6fa"

bspc config split_ratio             0.5

bspc config focus_follows_pointer   true
bspc config pointer_modifier        super

bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config paddingless_moncole     false

bspc rule -a firefox desktop=^2 state=monocle 
bspc rule -a Thunar desktop=^3 


# Set system vars for polybar
"$HOME"/.config/bspwm/src/SetSysVars

# Load current theme
"${HOME}"/.config/bspwm/rices/"${RICETHEME}"/Theme.sh

# Launch sxhkd daemon
pidof -q sxhkd || { sxhkd -c "${HOME}"/.config/bspwm/sxhkdrc & }

# Launch picom
pidof -q picom || { picom --config "${HOME}"/.config/bspwm/picom.conf & }

