-- BASIC
require('config.lazy')
require('config.mappings')
require('config.configs')
require('config.colors')

-- Plugins
require('plugins.neotree')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.mason')
require('plugins.telescope')
require('plugins.nullls')
require('plugins.dashboard')
require('plugins.buffline')
require('plugins.comments')
require('plugins.toggleterm')
require('plugins.autotags')
require('plugins.autopairs')
require('plugins.lualine')
